import { isValidContentSource } from './channelContentSourceValidator.js';
import {
  isValidBuildStrategy,
  isValidContentFilterArray,
  isValidPlaybackMode,
  isValidSortOrder,
} from './channelValueValidators.js';
import {
  CHANNEL_ERROR_MESSAGES,
  MAX_CHANNEL_NUMBER,
  MIN_CHANNEL_NUMBER,
} from './constants.js';
import type { ChannelCreateInput } from './types.js';

export type ChannelImportNormalizationResult =
  | { ok: true; channels: ChannelCreateInput[]; skippedCount: number }
  | { ok: false; error: string };

export class ChannelImportNormalizer {
  public normalizePayload(data: string): ChannelImportNormalizationResult {
    let parsed: unknown;
    try {
      parsed = JSON.parse(data);
    } catch {
      return { ok: false, error: CHANNEL_ERROR_MESSAGES.INVALID_IMPORT_DATA };
    }

    if (!Array.isArray(parsed)) {
      return { ok: false, error: CHANNEL_ERROR_MESSAGES.INVALID_IMPORT_DATA };
    }

    const channels: ChannelCreateInput[] = [];
    let skippedCount = 0;
    for (const item of parsed) {
      const channel = this.buildCreateInput(item);
      if (channel) {
        channels.push(channel);
      } else {
        skippedCount++;
      }
    }
    return { ok: true, channels, skippedCount };
  }

  public buildCreateInput(item: unknown): ChannelCreateInput | null {
    if (!item || typeof item !== 'object') {
      return null;
    }

    const record = item as Record<string, unknown>;
    const contentSource = record.contentSource;
    if (!isValidContentSource(contentSource)) {
      return null;
    }

    const channel: ChannelCreateInput = { contentSource };

    if (isValidChannelNumber(record.number)) {
      channel.number = record.number;
    }
    if (typeof record.name === 'string') channel.name = record.name;
    if (typeof record.description === 'string') channel.description = record.description;
    if (typeof record.isAutoGenerated === 'boolean') channel.isAutoGenerated = record.isAutoGenerated;
    if (typeof record.icon === 'string') channel.icon = record.icon;
    if (typeof record.color === 'string') channel.color = record.color;
    if (isValidBuildStrategy(record.buildStrategy)) channel.buildStrategy = record.buildStrategy;
    if (typeof record.sourceLibraryId === 'string') channel.sourceLibraryId = record.sourceLibraryId;
    if (typeof record.sourceLibraryName === 'string') channel.sourceLibraryName = record.sourceLibraryName;
    if (typeof record.lineupReplicaIndex === 'number' && Number.isFinite(record.lineupReplicaIndex)) {
      channel.lineupReplicaIndex = record.lineupReplicaIndex;
    }
    if (typeof record.isPlaybackModeVariant === 'boolean') {
      channel.isPlaybackModeVariant = record.isPlaybackModeVariant;
    }

    const playbackMode = isValidPlaybackMode(record.playbackMode) ? record.playbackMode : undefined;
    if (playbackMode !== undefined) channel.playbackMode = playbackMode;
    if (typeof record.shuffleSeed === 'number' && Number.isFinite(record.shuffleSeed)) {
      channel.shuffleSeed = record.shuffleSeed;
    }
    if (
      playbackMode === 'block' &&
      isPositiveInteger(record.blockSize)
    ) {
      channel.blockSize = record.blockSize;
    }
    if (typeof record.phaseSeed === 'number' && Number.isFinite(record.phaseSeed)) {
      channel.phaseSeed = record.phaseSeed;
    }
    if (typeof record.startTimeAnchor === 'number' && Number.isFinite(record.startTimeAnchor)) {
      channel.startTimeAnchor = record.startTimeAnchor;
    }
    if (isValidContentFilterArray(record.contentFilters)) {
      channel.contentFilters = record.contentFilters;
    }
    if (isValidSortOrder(record.sortOrder)) {
      channel.sortOrder = record.sortOrder;
    }
    if (typeof record.skipIntros === 'boolean') channel.skipIntros = record.skipIntros;
    if (typeof record.skipCredits === 'boolean') channel.skipCredits = record.skipCredits;
    if (isPositiveInteger(record.maxEpisodeRunTimeMs)) {
      channel.maxEpisodeRunTimeMs = record.maxEpisodeRunTimeMs;
    }
    if (isPositiveInteger(record.minEpisodeRunTimeMs)) {
      channel.minEpisodeRunTimeMs = record.minEpisodeRunTimeMs;
    }

    return channel;
  }

  public formatErrorMessage(error: unknown): string {
    if (error instanceof Error) {
      return error.message;
    }
    return String(error);
  }
}

function isValidChannelNumber(value: unknown): value is number {
  return (
    typeof value === 'number' &&
    Number.isFinite(value) &&
    Number.isInteger(value) &&
    value >= MIN_CHANNEL_NUMBER &&
    value <= MAX_CHANNEL_NUMBER
  );
}

function isPositiveInteger(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value) && Number.isInteger(value) && value > 0;
}
