import type {
  ChannelConfig,
  ChannelContentSource,
  ContentFilter,
  ManualContentItem,
  ResolvedChannelContent,
  ResolvedContentItem,
} from './types.js';

export function cloneChannelForOwnership(channel: ChannelConfig): ChannelConfig {
  const cloned: ChannelConfig = {
    id: channel.id,
    number: channel.number,
    name: channel.name,
    contentSource: cloneContentSource(channel.contentSource),
    playbackMode: channel.playbackMode,
    startTimeAnchor: channel.startTimeAnchor,
    skipIntros: channel.skipIntros,
    skipCredits: channel.skipCredits,
    createdAt: channel.createdAt,
    updatedAt: channel.updatedAt,
    lastContentRefresh: channel.lastContentRefresh,
    itemCount: channel.itemCount,
    totalDurationMs: channel.totalDurationMs,
  };

  if (channel.description !== undefined) cloned.description = channel.description;
  if (channel.isAutoGenerated !== undefined) cloned.isAutoGenerated = channel.isAutoGenerated;
  if (channel.icon !== undefined) cloned.icon = channel.icon;
  if (channel.color !== undefined) cloned.color = channel.color;
  if (channel.buildStrategy !== undefined) cloned.buildStrategy = channel.buildStrategy;
  if (channel.sourceLibraryId !== undefined) cloned.sourceLibraryId = channel.sourceLibraryId;
  if (channel.sourceLibraryName !== undefined) cloned.sourceLibraryName = channel.sourceLibraryName;
  if (channel.lineupReplicaIndex !== undefined) cloned.lineupReplicaIndex = channel.lineupReplicaIndex;
  if (channel.isPlaybackModeVariant !== undefined) cloned.isPlaybackModeVariant = channel.isPlaybackModeVariant;
  if (channel.shuffleSeed !== undefined) cloned.shuffleSeed = channel.shuffleSeed;
  if (channel.blockSize !== undefined) cloned.blockSize = channel.blockSize;
  if (channel.phaseSeed !== undefined) cloned.phaseSeed = channel.phaseSeed;
  if (channel.contentFilters !== undefined) cloned.contentFilters = cloneContentFilters(channel.contentFilters);
  if (channel.sortOrder !== undefined) cloned.sortOrder = channel.sortOrder;
  if (channel.maxEpisodeRunTimeMs !== undefined) cloned.maxEpisodeRunTimeMs = channel.maxEpisodeRunTimeMs;
  if (channel.minEpisodeRunTimeMs !== undefined) cloned.minEpisodeRunTimeMs = channel.minEpisodeRunTimeMs;

  return cloned;
}

export function cloneContentFilters(filters: ContentFilter[]): ContentFilter[] {
  return filters.map((filter) => ({
    field: filter.field,
    operator: filter.operator,
    value: filter.value,
  }));
}

export function cloneContentSource(source: ChannelContentSource): ChannelContentSource {
  switch (source.type) {
    case 'library':
      return {
        type: 'library',
        libraryId: source.libraryId,
        libraryType: source.libraryType,
        includeWatched: source.includeWatched,
        ...(source.libraryFilter ? { libraryFilter: { ...source.libraryFilter } } : {}),
      };
    case 'manual':
      return {
        type: 'manual',
        items: source.items.map(cloneManualContentItem),
      };
    case 'mixed':
      return {
        type: 'mixed',
        mixMode: source.mixMode,
        sources: source.sources.map(cloneContentSource),
      };
    case 'show':
      return {
        type: 'show',
        showKey: source.showKey,
        showName: source.showName,
        ...(source.seasonFilter ? { seasonFilter: [...source.seasonFilter] } : {}),
      };
    case 'collection':
      return {
        type: 'collection',
        collectionKey: source.collectionKey,
        collectionName: source.collectionName,
      };
    case 'playlist':
      return {
        type: 'playlist',
        playlistKey: source.playlistKey,
        playlistName: source.playlistName,
      };
  }
}

export function cloneResolvedItem(
  item: ResolvedContentItem,
  scheduledIndex = item.scheduledIndex,
): ResolvedContentItem {
  const cloned: ResolvedContentItem = {
    ratingKey: item.ratingKey,
    type: item.type,
    title: item.title,
    fullTitle: item.fullTitle,
    durationMs: item.durationMs,
    thumb: item.thumb,
    year: item.year,
    scheduledIndex,
  };
  if (item.showTitle !== undefined) cloned.showTitle = item.showTitle;
  if (item.showThumb !== undefined) cloned.showThumb = item.showThumb;
  if (item.art !== undefined) cloned.art = item.art;
  if (item.clearLogo !== undefined) cloned.clearLogo = item.clearLogo;
  if (item.seasonNumber !== undefined) cloned.seasonNumber = item.seasonNumber;
  if (item.episodeNumber !== undefined) cloned.episodeNumber = item.episodeNumber;
  if (item.rating !== undefined) cloned.rating = item.rating;
  if (item.contentRating !== undefined) cloned.contentRating = item.contentRating;
  if (item.genres) {
    cloned.genres = [...item.genres];
  }
  if (item.directors) {
    cloned.directors = [...item.directors];
  }
  if (item.mediaInfo) {
    cloned.mediaInfo = {};
    if (item.mediaInfo.resolution !== undefined) cloned.mediaInfo.resolution = item.mediaInfo.resolution;
    if (item.mediaInfo.hdr !== undefined) cloned.mediaInfo.hdr = item.mediaInfo.hdr;
    if (item.mediaInfo.dvProfile !== undefined) cloned.mediaInfo.dvProfile = item.mediaInfo.dvProfile;
    if (item.mediaInfo.audioCodec !== undefined) cloned.mediaInfo.audioCodec = item.mediaInfo.audioCodec;
    if (item.mediaInfo.audioChannels !== undefined) cloned.mediaInfo.audioChannels = item.mediaInfo.audioChannels;
    if (item.mediaInfo.audioTrackTitle !== undefined) cloned.mediaInfo.audioTrackTitle = item.mediaInfo.audioTrackTitle;
  }
  if (item.watched !== undefined) cloned.watched = item.watched;
  if (item.addedAt !== undefined) cloned.addedAt = item.addedAt;
  if (item.summary !== undefined) cloned.summary = item.summary;
  return cloned;
}

export function cloneResolvedItems(items: ReadonlyArray<ResolvedContentItem>): ResolvedContentItem[] {
  return items.map((item, index) => cloneResolvedItem(item, item.scheduledIndex ?? index));
}

export function cloneResolvedContent(
  content: ResolvedChannelContent,
  overrides?: Partial<Pick<ResolvedChannelContent, 'fromCache' | 'isStale' | 'cacheReason'>>,
): ResolvedChannelContent {
  const cloned: ResolvedChannelContent = {
    ...content,
    items: cloneResolvedItems(content.items),
    orderedItems: cloneResolvedItems(content.orderedItems),
  };
  const fromCache = overrides?.fromCache ?? content.fromCache;
  const isStale = overrides?.isStale ?? content.isStale;
  const cacheReason = overrides?.cacheReason ?? content.cacheReason;
  if (fromCache !== undefined) {
    cloned.fromCache = fromCache;
  }
  if (isStale !== undefined) {
    cloned.isStale = isStale;
  }
  if (cacheReason !== undefined) {
    cloned.cacheReason = cacheReason;
  }
  return cloned;
}

function cloneManualContentItem(item: ManualContentItem): ManualContentItem {
  return {
    ratingKey: item.ratingKey,
    title: item.title,
    durationMs: item.durationMs,
  };
}
