export type PlaybackMode = 'sequential' | 'shuffle' | 'block' | 'random';

export type DomainPlexMediaType = 'movie' | 'show' | 'episode';

export type BuildStrategy =
  | 'collections'
  | 'playlists'
  | 'genres'
  | 'directors'
  | 'decades'
  | 'recentlyAdded'
  | 'studios'
  | 'actors'
  | 'libraryFallback';

export type FilterOperator =
  | 'eq'
  | 'neq'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'contains'
  | 'notContains';

export type FilterField =
  | 'year'
  | 'rating'
  | 'contentRating'
  | 'genre'
  | 'director'
  | 'duration'
  | 'watched'
  | 'addedAt';

export type SortOrder =
  | 'title_asc'
  | 'title_desc'
  | 'year_asc'
  | 'year_desc'
  | 'added_asc'
  | 'added_desc'
  | 'duration_asc'
  | 'duration_desc'
  | 'episode_order';

export interface ContentFilter {
  field: FilterField;
  operator: FilterOperator;
  value: string | number | boolean;
}

interface BaseContentSource {
  type: string;
}

export interface LibraryContentSource extends BaseContentSource {
  type: 'library';
  libraryId: string;
  libraryType: 'movie' | 'show';
  includeWatched: boolean;
  libraryFilter?: Record<string, string | number>;
}

export interface CollectionContentSource extends BaseContentSource {
  type: 'collection';
  collectionKey: string;
  collectionName: string;
}

export interface ShowContentSource extends BaseContentSource {
  type: 'show';
  showKey: string;
  showName: string;
  seasonFilter?: number[];
}

export interface PlaylistContentSource extends BaseContentSource {
  type: 'playlist';
  playlistKey: string;
  playlistName: string;
}

export interface ManualContentItem {
  ratingKey: string;
  title: string;
  durationMs: number;
}

export interface ManualContentSource extends BaseContentSource {
  type: 'manual';
  items: ManualContentItem[];
}

export interface MixedContentSource extends BaseContentSource {
  type: 'mixed';
  sources: ChannelContentSource[];
  mixMode: 'interleave' | 'sequential';
}

export type ChannelContentSource =
  | LibraryContentSource
  | CollectionContentSource
  | ShowContentSource
  | PlaylistContentSource
  | ManualContentSource
  | MixedContentSource;

export interface ChannelConfig {
  id: string;
  number: number;
  name: string;
  description?: string;
  isAutoGenerated?: boolean;
  icon?: string;
  color?: string;
  buildStrategy?: BuildStrategy;
  sourceLibraryId?: string;
  sourceLibraryName?: string;
  lineupReplicaIndex?: number;
  isPlaybackModeVariant?: boolean;
  contentSource: ChannelContentSource;
  playbackMode: PlaybackMode;
  shuffleSeed?: number;
  blockSize?: number;
  phaseSeed?: number;
  startTimeAnchor: number;
  contentFilters?: ContentFilter[];
  sortOrder?: SortOrder;
  skipIntros: boolean;
  skipCredits: boolean;
  maxEpisodeRunTimeMs?: number;
  minEpisodeRunTimeMs?: number;
  createdAt: number;
  updatedAt: number;
  lastContentRefresh: number;
  itemCount: number;
  totalDurationMs: number;
}

type ChannelCreateOptionalField =
  | 'number'
  | 'name'
  | 'description'
  | 'isAutoGenerated'
  | 'icon'
  | 'color'
  | 'buildStrategy'
  | 'sourceLibraryId'
  | 'sourceLibraryName'
  | 'lineupReplicaIndex'
  | 'isPlaybackModeVariant'
  | 'playbackMode'
  | 'shuffleSeed'
  | 'blockSize'
  | 'phaseSeed'
  | 'startTimeAnchor'
  | 'contentFilters'
  | 'sortOrder'
  | 'skipIntros'
  | 'skipCredits'
  | 'maxEpisodeRunTimeMs'
  | 'minEpisodeRunTimeMs';

type ChannelWritableField = ChannelCreateOptionalField | 'contentSource';

export interface ChannelCreateInput
  extends Pick<ChannelConfig, 'contentSource'>,
    Partial<Pick<ChannelConfig, ChannelCreateOptionalField>> {}

export type ChannelUpdateInput = Partial<Pick<ChannelConfig, ChannelWritableField>>;

export interface ResolvedContentItem {
  ratingKey: string;
  type: DomainPlexMediaType;
  title: string;
  fullTitle: string;
  showTitle?: string;
  showThumb?: string | null;
  durationMs: number;
  thumb: string | null;
  art?: string | null;
  clearLogo?: string | null;
  year: number;
  seasonNumber?: number;
  episodeNumber?: number;
  scheduledIndex: number;
  rating?: number;
  contentRating?: string;
  genres?: string[];
  directors?: string[];
  summary?: string;
  mediaInfo?: {
    resolution?: string;
    hdr?: string;
    dvProfile?: string;
    audioCodec?: string;
    audioChannels?: number;
    audioTrackTitle?: string;
  };
  watched?: boolean;
  addedAt?: number;
}

export interface ResolvedChannelContent {
  channelId: string;
  resolvedAt: number;
  items: ResolvedContentItem[];
  totalDurationMs: number;
  orderedItems: ResolvedContentItem[];
  fromCache?: boolean;
  isStale?: boolean;
  cacheReason?: 'fresh' | 'network_error' | 'content_unavailable';
}

export interface ImportResult {
  success: boolean;
  importedCount: number;
  skippedCount: number;
  errors: string[];
}

export interface ChannelManagerEventMap {
  channelCreated: ChannelConfig;
  channelUpdated: ChannelConfig;
  channelDeleted: string;
  channelSwitch: { channel: ChannelConfig; index: number };
  contentResolved: ResolvedChannelContent;
  persistenceWarning: {
    message: string;
    code: string;
    isQuotaError: boolean;
    timestamp: number;
  };
}

export interface ChannelManagerState {
  channels: Map<string, ChannelConfig>;
  currentChannelId: string | null;
  channelOrder: string[];
}

export interface StoredChannelData {
  channels: ChannelConfig[];
  channelOrder: string[];
  currentChannelId: string | null;
  savedAt: number;
}
