import test from 'node:test';
import assert from 'node:assert/strict';

import { PLAYER_RENDERER_INTENTS } from '../../contracts/ipc.js';
import {
  PLAYER_COMMAND_VALUES,
  PLAYER_ERROR_CATEGORIES,
  PLAYER_FORBIDDEN_PRIVILEGED_FIELD_KEYS,
  PLAYER_STATUS_VALUES,
  PLAYER_TRACK_DELIVERY_TYPE_VALUES,
  PLAYER_TRACK_KIND_VALUES,
} from '../../contracts/player.js';
import { SHELL_STATUS_VALUES } from '../../contracts/shell.js';
import preloadVocabulary from '../../preload/vocabulary.cjs';

const {
  PLAYER_COMMAND_VALUES: PRELOAD_PLAYER_COMMAND_VALUES,
  PLAYER_ERROR_CATEGORIES: PRELOAD_PLAYER_ERROR_CATEGORIES,
  PLAYER_FORBIDDEN_PRIVILEGED_FIELD_KEYS: PRELOAD_PLAYER_FORBIDDEN_PRIVILEGED_FIELD_KEYS,
  PLAYER_RENDERER_INTENT_VALUES: PRELOAD_PLAYER_RENDERER_INTENT_VALUES,
  PLAYER_STATUS_VALUES: PRELOAD_PLAYER_STATUS_VALUES,
  PLAYER_TRACK_DELIVERY_TYPE_VALUES: PRELOAD_PLAYER_TRACK_DELIVERY_TYPE_VALUES,
  PLAYER_TRACK_KIND_VALUES: PRELOAD_PLAYER_TRACK_KIND_VALUES,
  SHELL_STATUS_VALUES: PRELOAD_SHELL_STATUS_VALUES,
} = preloadVocabulary;

test('preload guard vocabulary matches contract vocabulary', () => {
  assert.deepEqual([...PRELOAD_SHELL_STATUS_VALUES], [...SHELL_STATUS_VALUES]);
  assert.deepEqual([...PRELOAD_PLAYER_ERROR_CATEGORIES], [...PLAYER_ERROR_CATEGORIES]);
  assert.deepEqual(
    [...PRELOAD_PLAYER_FORBIDDEN_PRIVILEGED_FIELD_KEYS],
    [...PLAYER_FORBIDDEN_PRIVILEGED_FIELD_KEYS],
  );
  assert.deepEqual([...PRELOAD_PLAYER_STATUS_VALUES], [...PLAYER_STATUS_VALUES]);
  assert.deepEqual([...PRELOAD_PLAYER_COMMAND_VALUES], [...PLAYER_COMMAND_VALUES]);
  assert.deepEqual([...PRELOAD_PLAYER_RENDERER_INTENT_VALUES], [...PLAYER_RENDERER_INTENTS]);
  assert.deepEqual([...PRELOAD_PLAYER_TRACK_KIND_VALUES], [...PLAYER_TRACK_KIND_VALUES]);
  assert.deepEqual(
    [...PRELOAD_PLAYER_TRACK_DELIVERY_TYPE_VALUES],
    [...PLAYER_TRACK_DELIVERY_TYPE_VALUES],
  );
});
