export const desktopArchitectureRules = {
  version: '2026-05-11-rd-11-domain-boundary',
  domainBoundary: {
    files: ['src/domain/**/*.ts'],
    forbidNodeBuiltins: true,
    forbidNonLiteralDynamicImports: true,
    forbidGlobalThisProperties: true,
    forbiddenGlobals: [
      'window',
      'document',
      'localStorage',
      'sessionStorage',
      'globalThis',
      'process',
      'Buffer',
      'require',
      'global',
      '__dirname',
      '__filename',
    ],
    forbiddenImportPatterns: [
      'electron',
      'src/main',
      'src/main/**',
      'src/preload',
      'src/preload/**',
      'src/renderer',
      'src/renderer/**',
      'src/native-helper',
      'src/native-helper/**',
      '**/main',
      '**/main/**',
      '**/preload',
      '**/preload/**',
      '**/renderer',
      '**/renderer/**',
      '**/native-helper',
      '**/native-helper/**',
      '../main',
      '../main/**',
      '../preload',
      '../preload/**',
      '../renderer',
      '../renderer/**',
      '../native-helper',
      '../native-helper/**',
    ],
  },
  rendererBoundary: {
    files: ['src/renderer/**/*.ts', 'src/renderer/**/*.tsx'],
    forbidNodeBuiltins: true,
    forbiddenGlobals: ['Buffer', 'process', 'require', '__dirname', '__filename', 'global'],
    forbiddenImportPatterns: [
      'electron',
      'src/main',
      'src/main/**',
      'src/preload',
      'src/preload/**',
      'src/native-helper',
      'src/native-helper/**',
      '**/main',
      '**/main/**',
      '**/preload',
      '**/preload/**',
      '**/native-helper',
      '**/native-helper/**',
      '../main',
      '../main/**',
      '../preload',
      '../preload/**',
      '../native-helper',
      '../native-helper/**',
    ],
  },
  preloadBoundary: {
    files: ['src/preload/**/*.ts', 'src/preload/**/*.cts'],
    forbiddenImportPatterns: [
      'src/renderer',
      'src/renderer/**',
      'src/native-helper',
      'src/native-helper/**',
      '**/renderer',
      '**/renderer/**',
      '**/native-helper',
      '**/native-helper/**',
      '../renderer',
      '../renderer/**',
      '../native-helper',
      '../native-helper/**',
    ],
  },
  mainBoundary: {
    files: ['src/main/**/*.ts'],
    forbiddenImportPatterns: [
      'src/renderer',
      'src/renderer/**',
      '**/renderer',
      '**/renderer/**',
      '../renderer',
      '../renderer/**',
    ],
  },
  nativeHelperBoundary: {
    files: ['src/native-helper/**/*.ts'],
    forbiddenImportPatterns: [
      'src/renderer',
      'src/renderer/**',
      'src/preload',
      'src/preload/**',
      '**/renderer',
      '**/renderer/**',
      '**/preload',
      '**/preload/**',
      '../renderer',
      '../renderer/**',
      '../preload',
      '../preload/**',
    ],
  },
};
