/**
 * Data-owned architecture policy: production boundaries, test owners, and
 * named integration seams stay declarative so verifier behavior is reviewable
 * without reading ESLint config generation code.
 */
export const desktopArchitectureRules = {
  version: '2026-05-11-f-004-test-owner-boundaries',
  domainBoundary: {
    files: ['src/domain/**/*.ts'],
    forbidNodeBuiltins: true,
    forbidNonLiteralDynamicImports: true,
    forbidGlobalThisProperties: true,
    forbiddenGlobals: [
      'window',
      'document',
      'localStorage',
      'sessionStorage',
      'globalThis',
      'process',
      'Buffer',
      'require',
      'global',
      '__dirname',
      '__filename',
      'AbortController',
      'AbortSignal',
      'fetch',
      'setTimeout',
      'clearTimeout',
      'setInterval',
      'clearInterval',
      'URL',
      'URLSearchParams',
      'Headers',
      'Request',
      'Response',
      'WebSocket',
      'EventSource',
      'crypto',
      'navigator',
      'performance',
    ],
    forbiddenImportPatterns: [
      'electron',
      'src/main',
      'src/main/**',
      'src/preload',
      'src/preload/**',
      'src/renderer',
      'src/renderer/**',
      'src/native-helper',
      'src/native-helper/**',
      '**/main',
      '**/main/**',
      '**/preload',
      '**/preload/**',
      '**/renderer',
      '**/renderer/**',
      '**/native-helper',
      '**/native-helper/**',
      '../main',
      '../main/**',
      '../preload',
      '../preload/**',
      '../renderer',
      '../renderer/**',
      '../native-helper',
      '../native-helper/**',
    ],
  },
  rendererBoundary: {
    files: ['src/renderer/**/*.ts', 'src/renderer/**/*.tsx'],
    forbidNodeBuiltins: true,
    forbidNonLiteralDynamicImports: true,
    forbiddenGlobals: ['Buffer', 'process', 'require', '__dirname', '__filename', 'global'],
    forbiddenImportPatterns: [
      'electron',
      'src/main',
      'src/main/**',
      'src/preload',
      'src/preload/**',
      'src/native-helper',
      'src/native-helper/**',
      '**/main',
      '**/main/**',
      '**/preload',
      '**/preload/**',
      '**/native-helper',
      '**/native-helper/**',
      '../main',
      '../main/**',
      '../preload',
      '../preload/**',
      '../native-helper',
      '../native-helper/**',
    ],
  },
  preloadBoundary: {
    files: ['src/preload/**/*.ts', 'src/preload/**/*.cts'],
    forbidNonLiteralDynamicImports: true,
    forbiddenImportPatterns: [
      'src/renderer',
      'src/renderer/**',
      'src/native-helper',
      'src/native-helper/**',
      '**/renderer',
      '**/renderer/**',
      '**/native-helper',
      '**/native-helper/**',
      '../renderer',
      '../renderer/**',
      '../native-helper',
      '../native-helper/**',
    ],
  },
  mainBoundary: {
    files: ['src/main/**/*.ts'],
    forbidNonLiteralDynamicImports: true,
    forbiddenImportPatterns: [
      'src/renderer',
      'src/renderer/**',
      '**/renderer',
      '**/renderer/**',
      '../renderer',
      '../renderer/**',
    ],
  },
  nativeHelperBoundary: {
    files: ['src/native-helper/**/*.ts'],
    forbidNonLiteralDynamicImports: true,
    forbiddenImportPatterns: [
      'src/renderer',
      'src/renderer/**',
      'src/preload',
      'src/preload/**',
      '**/renderer',
      '**/renderer/**',
      '**/preload',
      '**/preload/**',
      '../renderer',
      '../renderer/**',
      '../preload',
      '../preload/**',
    ],
  },
  testOwners: [
    {
      owner: 'contracts',
      files: ['src/__tests__/contracts/**/*.test.ts'],
      allowedNodeBuiltins: ['node:test', 'node:assert', 'node:assert/strict'],
      forbiddenImportPatterns: [
        'electron',
        'src/domain',
        'src/domain/**',
        'src/main',
        'src/main/**',
        'src/preload',
        'src/preload/**',
        'src/renderer',
        'src/renderer/**',
        'src/native-helper',
        'src/native-helper/**',
        '**/domain',
        '**/domain/**',
        '**/main',
        '**/main/**',
        '**/preload',
        '**/preload/**',
        '**/renderer',
        '**/renderer/**',
        '**/native-helper',
        '**/native-helper/**',
      ],
    },
    {
      owner: 'domain',
      files: ['src/__tests__/domain/**/*.test.ts'],
      allowedNodeBuiltins: ['node:test', 'node:assert', 'node:assert/strict'],
      forbiddenImportPatterns: [
        'electron',
        'src/contracts',
        'src/contracts/**',
        'src/main',
        'src/main/**',
        'src/preload',
        'src/preload/**',
        'src/renderer',
        'src/renderer/**',
        'src/native-helper',
        'src/native-helper/**',
        '**/contracts',
        '**/contracts/**',
        '**/main',
        '**/main/**',
        '**/preload',
        '**/preload/**',
        '**/renderer',
        '**/renderer/**',
        '**/native-helper',
        '**/native-helper/**',
      ],
    },
    {
      owner: 'main',
      files: ['src/__tests__/main/**/*.test.ts'],
      forbiddenImportPatterns: [
        'src/preload',
        'src/preload/**',
        'src/renderer',
        'src/renderer/**',
        'src/native-helper',
        'src/native-helper/**',
        '**/preload',
        '**/preload/**',
        '**/renderer',
        '**/renderer/**',
        '**/native-helper',
        '**/native-helper/**',
      ],
    },
    {
      owner: 'preload',
      files: ['src/__tests__/preload/**/*.test.ts'],
      allowedNodeBuiltins: ['node:test', 'node:assert', 'node:assert/strict'],
      forbiddenImportPatterns: [
        'src/domain',
        'src/domain/**',
        'src/main',
        'src/main/**',
        'src/renderer',
        'src/renderer/**',
        'src/native-helper',
        'src/native-helper/**',
        '**/domain',
        '**/domain/**',
        '**/main',
        '**/main/**',
        '**/renderer',
        '**/renderer/**',
        '**/native-helper',
        '**/native-helper/**',
      ],
    },
    {
      owner: 'renderer',
      files: ['src/__tests__/renderer/**/*.test.ts'],
      allowedNodeBuiltins: ['node:test', 'node:assert', 'node:assert/strict'],
      forbiddenImportPatterns: [
        'electron',
        'src/domain',
        'src/domain/**',
        'src/main',
        'src/main/**',
        'src/preload',
        'src/preload/**',
        'src/native-helper',
        'src/native-helper/**',
        '**/domain',
        '**/domain/**',
        '**/main',
        '**/main/**',
        '**/preload',
        '**/preload/**',
        '**/native-helper',
        '**/native-helper/**',
      ],
    },
  ],
  integrationSeams: [
    {
      label: 'preload-contract-vocabulary-parity',
      files: ['src/__tests__/integration/preloadContractVocabulary.test.ts'],
      allowedNodeBuiltins: ['node:test', 'node:assert', 'node:assert/strict', 'node:fs'],
      allowedImportPatterns: [
        'typescript',
        '../../contracts/**',
      ],
      ownerPair: ['preload', 'contracts'],
      rationale:
        'Preload entrypoint runtime guard vocabulary must stay in lockstep with renderer-safe contract vocabulary.',
      proofTestPath: 'src/__tests__/integration/preloadContractVocabulary.test.ts',
    },
  ],
  integrationTests: {
    files: ['src/__tests__/integration/**/*.test.ts'],
    allowedNodeBuiltins: ['node:test', 'node:assert', 'node:assert/strict'],
  },
};
