import type {
  FilterField,
  FilterOperator,
  PlaybackMode,
  SortOrder,
} from '../channel/types.js';

export type PersistedStringV1 = Readonly<{
  nfc: string;
  utf16: readonly number[];
}>;

export type ChannelBuilderStrategyKey =
  | 'collections'
  | 'playlists'
  | 'genres'
  | 'directors'
  | 'decades'
  | 'recentlyAdded'
  | 'studios'
  | 'actors';

export type ChannelBuilderStrategyScope = 'per-library' | 'cross-library';

export type ChannelBuilderStrategyConfig = Readonly<{
  enabled: boolean;
  priority: number;
  scope: ChannelBuilderStrategyScope;
}>;

export type ChannelBuilderExpansionConfig = Readonly<{
  addAlternateLineups: boolean;
  alternateLineupCopies: number;
  variantType: 'none' | 'sequential' | 'block';
  variantBlockSize: number;
}>;

export type ChannelBuilderSeriesOrderingConfig = Readonly<{
  basePlaybackMode: 'shuffle' | 'sequential' | 'block';
  baseBlockSize: number;
}>;

export type ChannelSetupConfig = Readonly<{
  serverId: string;
  selectedLibraryIds: readonly string[];
  maxChannels: number;
  minItemsPerChannel: number;
  buildMode: 'append' | 'replace' | 'merge';
  actorStudioCombineMode: 'separate' | 'combined';
  strategyConfig: Readonly<Record<ChannelBuilderStrategyKey, ChannelBuilderStrategyConfig>>;
  channelExpansion: ChannelBuilderExpansionConfig;
  seriesOrdering: ChannelBuilderSeriesOrderingConfig;
}>;

export type NormalizedChannelSetupConfig = ChannelSetupConfig;

export type ChannelSetupConfigContext = Readonly<{
  serverId: string;
  selectedLibraryIds: readonly string[];
}>;

export type ChannelBuilderProfileBinding = `profile-binding:${string}`;
export type ChannelBuilderServerBinding = `server-binding:${string}`;
export type ChannelBuilderLibrarySetBinding = `library-set-binding:${string}`;
export type ChannelBuilderFacetId =
  `${'library' | 'playlist' | 'collection' | 'genre' | 'director' | 'year' | 'studio' | 'actor' | 'recently-added'}:${string}`;
export type ChannelBuilderSourceIdentity = `source:${string}`;
export type ChannelBuilderTagSemanticGroupIdentity = `tag-group:${string}`;
export type ChannelBuilderContentFilterIdentity = `content-filters:${string}`;
export type ChannelBuilderCandidateIdentity = `candidate-identity:${string}`;
export type ChannelBuilderCandidateId = `candidate:${string}`;
export type ChannelBuilderPlanIdentity = `plan-identity:${string}`;

export type ChannelBuilderOriginBinding = Readonly<{
  profileBinding: ChannelBuilderProfileBinding;
  serverBinding: ChannelBuilderServerBinding;
  librarySetBinding: ChannelBuilderLibrarySetBinding;
}>;

export type ChannelBuilderContextBinding = Readonly<
  ChannelBuilderOriginBinding & { contextEpoch: number }
>;

export type ChannelBuilderSafeSourceLeafReference = Readonly<{
  kind: 'facet';
  facetId: ChannelBuilderFacetId | null;
  sourceIdentity: ChannelBuilderSourceIdentity;
}>;

export type ChannelBuilderSafeManualSourceReference = Readonly<{
  kind: 'manual';
  sourceIdentity: ChannelBuilderSourceIdentity;
  items: readonly ChannelBuilderSafeSourceLeafReference[];
}>;

export type ChannelBuilderSafeMixedSourceReference = Readonly<{
  kind: 'mixed';
  sourceIdentity: ChannelBuilderSourceIdentity;
  mixMode: 'sequential' | 'interleave';
  sources: readonly ChannelBuilderSafeSourceReference[];
}>;

export type ChannelBuilderSafeSourceReference =
  | ChannelBuilderSafeSourceLeafReference
  | ChannelBuilderSafeManualSourceReference
  | ChannelBuilderSafeMixedSourceReference;

export type ChannelBuilderChannelProvenanceV1 = Readonly<{
  schemaVersion: 1;
  identityVersion: 1;
  profileBinding: ChannelBuilderProfileBinding;
  serverBinding: ChannelBuilderServerBinding;
  librarySetBinding: ChannelBuilderLibrarySetBinding;
  sourceIdentity: ChannelBuilderSourceIdentity;
  candidateIdentity: ChannelBuilderCandidateIdentity;
}>;

type ExistingLineupCommon = Readonly<{
  id: string;
  number: number;
  name: string;
  playbackMode: PlaybackMode;
  contentFilterIdentity: ChannelBuilderContentFilterIdentity | null;
  sortOrder?: SortOrder;
  blockSize?: number;
  lineupReplicaIndex?: number;
  isPlaybackModeVariant?: boolean;
  isAutoGenerated?: boolean;
}>;

export type ChannelBuilderExistingLineupEntry =
  | Readonly<
      ExistingLineupCommon & {
        sourceDisposition: 'matchable';
        sourceReference: ChannelBuilderSafeSourceReference;
        builderProvenance: ChannelBuilderChannelProvenanceV1 | null;
      }
    >
  | Readonly<
      ExistingLineupCommon & {
        sourceDisposition: 'retained-unmatchable';
        sourceReference: null;
        builderProvenance: null;
      }
    >;

export type ChannelBuilderFacetWarningCode =
  | 'FACET_UNAVAILABLE'
  | 'FACET_PARTIAL_FAILURE'
  | 'FACET_DISCOVERY_TIMEOUT'
  | 'FACET_EMPTY'
  | 'FACET_CAP_REACHED'
  | 'FACET_MALFORMED_ENTRIES_OMITTED'
  | 'TV_PEOPLE_METADATA_INCOMPLETE';

export type ChannelBuilderLibraryFacet = Readonly<{
  facetId: ChannelBuilderFacetId;
  sourceIdentity: ChannelBuilderSourceIdentity;
  title: string;
  mediaType: 'movie' | 'show';
  contentCount: number;
}>;

export type ChannelBuilderPlaylistFacet = Readonly<{
  facetId: ChannelBuilderFacetId;
  sourceIdentity: ChannelBuilderSourceIdentity;
  title: string;
  itemCount: number;
  durationMs: number;
}>;

export type ChannelBuilderCollectionFacet = Readonly<{
  facetId: ChannelBuilderFacetId;
  sourceIdentity: ChannelBuilderSourceIdentity;
  libraryFacetId: ChannelBuilderFacetId;
  title: string;
  itemCount: number;
}>;

type ChannelBuilderTagFacetCommon = Readonly<{
  facetId: ChannelBuilderFacetId;
  sourceIdentity: ChannelBuilderSourceIdentity;
  libraryFacetId: ChannelBuilderFacetId;
  displayTitle: string;
  itemCount: number | null;
  episodeCount: number | null;
  distinctSeriesCount: number | null;
}>;

export type ChannelBuilderTagFacet =
  | Readonly<
      ChannelBuilderTagFacetCommon & {
        family: 'genre' | 'studio' | 'actor';
        semanticGroupIdentity: ChannelBuilderTagSemanticGroupIdentity;
        contentFilterIdentity: null;
        yearValue: null;
      }
    >
  | Readonly<
      ChannelBuilderTagFacetCommon & {
        family: 'director';
        semanticGroupIdentity: ChannelBuilderTagSemanticGroupIdentity;
        contentFilterIdentity: ChannelBuilderContentFilterIdentity;
        yearValue: null;
      }
    >
  | Readonly<
      ChannelBuilderTagFacetCommon & {
        family: 'year';
        semanticGroupIdentity: null;
        contentFilterIdentity: null;
        yearValue: number | null;
      }
    >;

export type ChannelBuilderRecentlyAddedFacet = Readonly<{
  facetId: ChannelBuilderFacetId;
  sourceIdentity: ChannelBuilderSourceIdentity;
  libraryFacetId: ChannelBuilderFacetId;
  itemCount: number;
}>;

export type ChannelBuilderFacetSnapshot = Readonly<{
  context: ChannelBuilderContextBinding;
  libraries: readonly ChannelBuilderLibraryFacet[];
  playlists: readonly ChannelBuilderPlaylistFacet[];
  collections: readonly ChannelBuilderCollectionFacet[];
  tags: readonly ChannelBuilderTagFacet[];
  recentlyAdded: readonly ChannelBuilderRecentlyAddedFacet[];
  aggregate: Readonly<{
    status: 'ready' | 'blocked' | 'slow';
    warningCodes: readonly ChannelBuilderFacetWarningCode[];
    omittedMalformedCount: number;
    omittedCappedCount: number | null;
  }>;
}>;

export type ChannelSetupWarningCode =
  | ChannelBuilderFacetWarningCode
  | 'EXISTING_SOURCE_UNMATCHABLE'
  | 'MIN_ITEMS_SKIPPED'
  | 'MAX_CHANNELS_REACHED'
  | 'PLAN_EMPTY'
  | 'MATERIALIZATION_SKIPPED'
  | 'GUIDE_REFRESH_FAILED';

export type ChannelSetupWarning = Readonly<{
  code: ChannelSetupWarningCode;
  phase: 'discovery' | 'planning' | 'materialization' | 'refresh';
  strategy: ChannelBuilderStrategyKey | null;
  affectedCount: number | null;
}>;

export type ChannelBuilderCandidateContentFilterPlan =
  | Readonly<{ kind: 'none'; contentFilterIdentity: null }>
  | Readonly<{
      kind: 'inline';
      contentFilterIdentity: ChannelBuilderContentFilterIdentity;
      filters: readonly ChannelBuilderNumericContentFilter[];
    }>
  | Readonly<{
      kind: 'main-index-reference';
      contentFilterIdentity: ChannelBuilderContentFilterIdentity;
      facetId: ChannelBuilderFacetId;
    }>;

export type ChannelBuilderNumericContentFilter = Readonly<{
  field: FilterField;
  operator: FilterOperator;
  value: number;
}>;

export type ChannelBuilderCandidateDraft = Readonly<{
  candidateId: ChannelBuilderCandidateId;
  candidateIdentity: ChannelBuilderCandidateIdentity;
  origin: ChannelBuilderOriginBinding;
  strategy: ChannelBuilderStrategyKey;
  displayName: string;
  sourceReference: ChannelBuilderSafeSourceReference;
  estimatedItemCount: number | null;
  playbackMode: PlaybackMode;
  shuffleSeed: number;
  contentFilterPlan: ChannelBuilderCandidateContentFilterPlan;
  sortOrder: SortOrder | null;
  blockSize: number | null;
  buildStrategy: ChannelBuilderStrategyKey | null;
  sourceLibraryId: string | null;
  sourceLibraryName: string | null;
  lineupReplicaIndex: 0 | 1 | 2 | 3 | null;
  isPlaybackModeVariant: boolean | null;
}>;

export type ChannelBuilderCandidateLedgerClassification =
  | 'matched-retained'
  | 'new-apply'
  | 'excluded';
export type ChannelBuilderCandidateExclusion =
  | 'minimum-items'
  | 'configured-capacity'
  | 'channel-number-capacity';

export type ChannelBuilderCandidateLedgerEntry = Readonly<{
  ordinal: number;
  candidateId: ChannelBuilderCandidateId;
  strategy: ChannelBuilderStrategyKey;
  sourceIdentity: ChannelBuilderSourceIdentity;
  classification: ChannelBuilderCandidateLedgerClassification;
  exclusion: ChannelBuilderCandidateExclusion | null;
  retainedChannelId: string | null;
}>;

export type ChannelBuilderExistingLedgerEntry = Readonly<{
  ordinal: number;
  existingChannelId: string;
  disposition: 'matched-retained' | 'unmatched-retained' | 'replace-remove';
  matchedCandidateId: ChannelBuilderCandidateId | null;
}>;

export type ChannelSetupReviewDiff = Readonly<{
  summary: Readonly<{ created: number; removed: number; unchanged: number }>;
  samples: Readonly<{
    created: readonly string[];
    removed: readonly string[];
    unchanged: readonly string[];
  }>;
}>;

export type ChannelBuilderPlannerInput = Readonly<{
  normalizedConfig: NormalizedChannelSetupConfig;
  facetSnapshot: ChannelBuilderFacetSnapshot;
  existingLineup: readonly ChannelBuilderExistingLineupEntry[];
  clock: Readonly<{ nowMs: number }>;
  seed: string;
}>;

export type ChannelBuilderPlannerOutput = Readonly<{
  status: 'ready' | 'slow' | 'blocked';
  planIdentity: ChannelBuilderPlanIdentity;
  candidateDrafts: readonly ChannelBuilderCandidateDraft[];
  applyCandidateIds: readonly ChannelBuilderCandidateId[];
  retainedMaterializationCandidateIds: readonly ChannelBuilderCandidateId[];
  candidateLedger: readonly ChannelBuilderCandidateLedgerEntry[];
  existingLedger: readonly ChannelBuilderExistingLedgerEntry[];
  diff: ChannelSetupReviewDiff;
  warnings: readonly ChannelSetupWarning[];
  reachedCap: boolean;
  capacity: Readonly<{
    requestedMaxChannels: number;
    effectiveMaxChannels: number;
    availableCreateSlots: number;
  }>;
}>;

export type ChannelBuilderPersistedStateV1 = Readonly<{
  schemaVersion: 1;
  normalizedConfig: NormalizedChannelSetupConfig;
  completedAtMs: number;
  profileBinding: ChannelBuilderProfileBinding;
  serverBinding: ChannelBuilderServerBinding;
  librarySetBinding: ChannelBuilderLibrarySetBinding;
  channelProvenance: Readonly<Record<string, ChannelBuilderChannelProvenanceV1>>;
}>;

function normalizeDisplayIntermediate(raw: string): string {
  return raw
    .normalize('NFC')
    // Display projection replaces C0, DEL, and C1 controls.
    // eslint-disable-next-line no-control-regex
    .replace(/[\u0000-\u001f\u007f-\u009f]/gu, ' ')
    .replace(/\s+/gu, ' ');
}

export function containsChannelBuilderCredentialMarker(raw: string): boolean {
  const normalized = normalizeDisplayIntermediate(raw);
  return /(^|[^A-Za-z0-9_])(?:bearer|token|authorization|headers?)(?=$|[^A-Za-z0-9_])/iu.test(
    normalized,
  );
}

function truncateUtf16WithoutSplittingSurrogate(raw: string, maxUtf16Units: number): string {
  if (raw.length <= maxUtf16Units) return raw;
  let end = maxUtf16Units;
  const previous = raw.charCodeAt(end - 1);
  const next = raw.charCodeAt(end);
  if (previous >= 0xd800 && previous <= 0xdbff && next >= 0xdc00 && next <= 0xdfff) {
    end -= 1;
  }
  return raw.slice(0, end);
}

export function projectChannelBuilderSafeDisplayString(
  raw: string,
  options: Readonly<{ fallback: string; maxUtf16Units: number }>,
): string {
  if (
    !Number.isInteger(options.maxUtf16Units) ||
    options.maxUtf16Units < 1 ||
    options.maxUtf16Units > 2_000
  ) {
    throw new TypeError('Invalid channel builder display limit.');
  }
  if (containsChannelBuilderCredentialMarker(raw)) return '[redacted]';
  const projected = normalizeDisplayIntermediate(raw)
    .replace(/</gu, '\u2039')
    .replace(/>/gu, '\u203a')
    .replace(/https?:\/\/\S+/giu, '[link]')
    .replace(/\s+/gu, ' ')
    .trim();
  const truncated = truncateUtf16WithoutSplittingSurrogate(
    projected,
    options.maxUtf16Units,
  );
  return truncated.length > 0 ? truncated : options.fallback;
}
