import type { ChannelSetupConfig } from '../../../contracts/channel.js';
import { MAX_CHANNEL_NUMBER, MIN_CHANNEL_NUMBER } from '../constants.js';
import { cloneContentFilters, cloneContentSource } from '../channelDomainClone.js';
import type { ChannelConfig, ChannelContentSource, ContentFilter } from '../types.js';
import type {
  ChannelSetupIdentityCandidate,
  ChannelSetupNumberAllocation,
  ChannelSetupPlanDiff,
  ChannelSetupPlannedChannel,
} from './types.js';

export function createChannelSetupIdentity(candidate: ChannelSetupIdentityCandidate): string {
  return stableSerialize({
    contentSource: normalizeSource(candidate.contentSource),
    contentFilters: normalizeFilters(candidate.contentFilters),
    sortOrder: candidate.sortOrder ?? null,
    lineupReplicaIndex: candidate.lineupReplicaIndex ?? 0,
    isPlaybackModeVariant: candidate.isPlaybackModeVariant === true,
    variantPlaybackMode: candidate.isPlaybackModeVariant === true ? candidate.playbackMode : null,
    variantBlockSize: candidate.isPlaybackModeVariant === true && candidate.playbackMode === 'block'
      ? candidate.blockSize ?? null
      : null,
  });
}

export function diffChannelSetupPlan(
  existingChannels: readonly ChannelConfig[],
  plannedChannels: readonly ChannelSetupPlannedChannel[],
  mode: ChannelSetupConfig['buildMode'],
): ChannelSetupPlanDiff {
  if (mode === 'replace') {
    return createDiff(mode, plannedChannels, [], [], existingChannels);
  }

  const queues = new Map<string, ChannelConfig[]>();
  for (const existing of existingChannels) {
    if (existing.isAutoGenerated !== true) continue;
    const identity = createChannelSetupIdentity(existing);
    const queue = queues.get(identity) ?? [];
    queue.push(existing);
    queues.set(identity, queue);
  }

  const created: ChannelSetupPlannedChannel[] = [];
  const matched: Array<{ existing: ChannelConfig; planned: ChannelSetupPlannedChannel }> = [];
  const matchedIds = new Set<string>();
  for (const planned of plannedChannels) {
    const queue = queues.get(createChannelSetupIdentity(planned));
    const existing = queue?.shift();
    if (!existing) {
      created.push(planned);
      continue;
    }
    matched.push({ existing, planned });
    matchedIds.add(existing.id);
  }
  const preserved = mode === 'append'
    ? [...existingChannels]
    : existingChannels.filter((channel) => !matchedIds.has(channel.id));
  return createDiff(mode, created, matched, preserved, []);
}

export function allocateChannelSetupNumbers(
  existingChannels: readonly Pick<ChannelConfig, 'number'>[],
  requestedCount: number,
  mode: ChannelSetupConfig['buildMode'],
): ChannelSetupNumberAllocation {
  const count = Number.isFinite(requestedCount) ? Math.max(0, Math.floor(requestedCount)) : 0;
  const reserved = mode === 'replace'
    ? new Set<number>()
    : new Set(existingChannels.map((channel) => channel.number));
  const numbers: number[] = [];
  for (let number = MIN_CHANNEL_NUMBER; number <= MAX_CHANNEL_NUMBER && numbers.length < count; number += 1) {
    if (!reserved.has(number)) numbers.push(number);
  }
  return { numbers, exhausted: numbers.length < count };
}

export function mergeChannelSetupMatch(
  existing: ChannelConfig,
  planned: ChannelSetupPlannedChannel,
  updatedAt: number,
): ChannelConfig {
  const merged: ChannelConfig = {
    ...existing,
    name: planned.name,
    isAutoGenerated: true,
    buildStrategy: planned.buildStrategy,
    contentSource: cloneContentSource(planned.contentSource),
    playbackMode: planned.playbackMode,
    shuffleSeed: planned.shuffleSeed,
    lineupReplicaIndex: planned.lineupReplicaIndex,
    isPlaybackModeVariant: planned.isPlaybackModeVariant,
    updatedAt,
  };
  copyOptional(merged, 'sourceLibraryId', planned.sourceLibraryId);
  copyOptional(merged, 'sourceLibraryName', planned.sourceLibraryName);
  copyOptional(merged, 'blockSize', planned.blockSize);
  copyOptional(merged, 'sortOrder', planned.sortOrder);
  if (planned.contentFilters === undefined) delete merged.contentFilters;
  else merged.contentFilters = cloneContentFilters(planned.contentFilters);
  return merged;
}

function createDiff(
  mode: ChannelSetupConfig['buildMode'],
  created: readonly ChannelSetupPlannedChannel[],
  matched: ChannelSetupPlanDiff['matched'],
  preserved: readonly ChannelConfig[],
  removed: readonly ChannelConfig[],
): ChannelSetupPlanDiff {
  const unchanged = mode === 'merge'
    ? [...preserved.map((channel) => channel.name), ...matched.map(({ planned }) => planned.name)]
    : preserved.map((channel) => channel.name);
  return {
    mode,
    created,
    matched,
    preserved,
    removed,
    summary: { created: created.length, removed: removed.length, unchanged: unchanged.length },
    samples: {
      created: created.slice(0, 6).map((channel) => channel.name),
      removed: removed.slice(0, 6).map((channel) => channel.name),
      unchanged: unchanged.slice(0, 6),
    },
  };
}

function copyOptional<TKey extends 'sourceLibraryId' | 'sourceLibraryName' | 'blockSize' | 'sortOrder'>(
  target: ChannelConfig,
  key: TKey,
  value: ChannelConfig[TKey],
): void {
  if (value === undefined) delete target[key];
  else target[key] = value;
}

function normalizeFilters(filters: ContentFilter[] | undefined): unknown {
  if (!filters || filters.length === 0) return null;
  return [...filters].sort((left, right) => stableSerialize(left).localeCompare(stableSerialize(right)));
}

function normalizeSource(source: ChannelContentSource): unknown {
  switch (source.type) {
    case 'library': return { ...source, libraryFilter: normalizeRecord(source.libraryFilter) };
    case 'collection': return { type: source.type, collectionKey: source.collectionKey };
    case 'playlist': return { type: source.type, playlistKey: source.playlistKey };
    case 'show': return { type: source.type, showKey: source.showKey, seasonFilter: source.seasonFilter ? [...source.seasonFilter].sort((a, b) => a - b) : null };
    case 'manual': return { type: source.type, items: [...source.items].sort((a, b) => a.ratingKey.localeCompare(b.ratingKey)) };
    case 'mixed': return {
      type: source.type,
      mixMode: source.mixMode,
      sources: source.sources.map(normalizeSource).sort((a, b) => stableSerialize(a).localeCompare(stableSerialize(b))),
    };
  }
}

function normalizeRecord(record: Record<string, string | number> | undefined): unknown {
  if (!record) return null;
  return Object.fromEntries(Object.entries(record).sort(([left], [right]) => left.localeCompare(right)));
}

function stableSerialize(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(stableSerialize).join(',')}]`;
  const record = value as Record<string, unknown>;
  return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${stableSerialize(record[key])}`).join(',')}}`;
}
