import type {
  ChannelSetupConfig,
  ChannelSetupEstimates,
  ChannelSetupStrategyKey,
} from '../../../contracts/channel.js';
import type {
  ChannelConfig,
  ContentFilter,
  PlaybackMode,
  SortOrder,
} from '../types.js';

export interface ChannelSetupLibraryFacet {
  id: string;
  title: string;
  type: 'movie' | 'show';
  itemCount: number | null;
}

export interface ChannelSetupNamedFacet {
  key: string;
  title: string;
  itemCount: number | null;
  seriesCount?: number | null;
}

export interface ChannelSetupPlaylistFacet extends ChannelSetupNamedFacet {}

export interface ChannelSetupFacetSnapshot {
  libraries: readonly ChannelSetupLibraryFacet[];
  playlists: readonly ChannelSetupPlaylistFacet[];
  collectionsByLibraryId: ReadonlyMap<string, readonly ChannelSetupNamedFacet[]>;
  genresByLibraryId: ReadonlyMap<string, readonly ChannelSetupNamedFacet[]>;
  directorsByLibraryId: ReadonlyMap<string, readonly ChannelSetupNamedFacet[]>;
  yearsByLibraryId: ReadonlyMap<string, readonly ChannelSetupNamedFacet[]>;
  studiosByLibraryId: ReadonlyMap<string, readonly ChannelSetupNamedFacet[]>;
  actorsByLibraryId: ReadonlyMap<string, readonly ChannelSetupNamedFacet[]>;
  warnings: readonly string[];
}

export interface ChannelSetupPlannedChannel
  extends Pick<ChannelConfig,
    | 'name'
    | 'contentSource'
    | 'playbackMode'
    | 'shuffleSeed'
    | 'sourceLibraryId'
    | 'sourceLibraryName'
    | 'contentFilters'
    | 'sortOrder'
    | 'blockSize'
    | 'lineupReplicaIndex'
    | 'isPlaybackModeVariant'> {
  buildStrategy: ChannelSetupStrategyKey;
  shuffleSeed: number;
  lineupReplicaIndex: number;
  isPlaybackModeVariant: boolean;
  isAutoGenerated: true;
  eligibleItemCount: number | null;
}

export interface ChannelSetupPlan {
  config: ChannelSetupConfig;
  channels: readonly ChannelSetupPlannedChannel[];
  estimates: ChannelSetupEstimates;
  eligibleGeneratedCount: number;
  selectedGeneratedCount: number;
  droppedByMinItemsCount: number;
  droppedByPlanCapCount: number;
  reachedMaxChannels: boolean;
  warnings: readonly string[];
}

export interface ChannelSetupIdentityCandidate {
  contentSource: ChannelConfig['contentSource'];
  contentFilters?: ContentFilter[];
  sortOrder?: SortOrder;
  playbackMode: PlaybackMode;
  blockSize?: number;
  lineupReplicaIndex?: number;
  isPlaybackModeVariant?: boolean;
}

export interface ChannelSetupPlanMatch {
  existing: ChannelConfig;
  planned: ChannelSetupPlannedChannel;
}

export interface ChannelSetupPlanDiff {
  mode: ChannelSetupConfig['buildMode'];
  created: readonly ChannelSetupPlannedChannel[];
  matched: readonly ChannelSetupPlanMatch[];
  preserved: readonly ChannelConfig[];
  removed: readonly ChannelConfig[];
  summary: { created: number; removed: number; unchanged: number };
  samples: { created: readonly string[]; removed: readonly string[]; unchanged: readonly string[] };
}

export interface ChannelSetupNumberAllocation {
  numbers: readonly number[];
  exhausted: boolean;
}
